### ISSUE TITLE
What files do I need to prepare in the folder -p /path_to_laser_experiment if I use unsupervised fine-tuning?

### ISSUE THREAD

**Issue by zxree** [Trikaldarshi/LASER#2]

**Comment by Trikaldarshi** [comment]
Hello,
Thanks for your interest in our work. I am not quite sure about your question. -p /path_to_laser_experiment is the path where you would like to store the output of your experiments. For example -p /user/xyz/exp1 something like that. You just need to follow the steps as mentioned in our repository. Let me know if you face any issues.

**Comment by zxree** [comment]
thank you

**Comment by zxree** [comment]
I have a pre-trained hubert model (.pt), how do I modify the configuration file to import the pre-trained model and continue the unsupervised fine-tuning?

**Comment by Trikaldarshi** [comment]
Did you install s3prl toolkit and tried the steps mentioned in the repository?

**Comment by zxree** [comment]
yes

**Comment by zxree** [comment]
**Sorry, I still don't quite know where to change my address.

**Comment by Trikaldarshi** [comment]
Can you be more specific please? Like in which step you are struggling?

**Comment by zxree** [comment]
![屏幕截图 2024-10-21 183705](https://github.com/user-attachments/assets/10d43e4e-4548-4542-8d3e-040bb96dcecf)

**Comment by zxree** [comment]
Thank you so much. 
When I run this step, I don't want to download the dataset from the internet, I have all my wav files in one directory, I have the pre-trained hubert model (.pt file) downloaded from the internet (but not in librispeech, but trained in another language), and I would like to fine-tune it further with my own audio, how do I change the address of the model, and the audio address

**Comment by zxree** [comment]
And，How do I organise my audio file structure？ Sorry to trouble you.

**Comment by Trikaldarshi** [comment]
Hello, no worries at all. In that case, you have to write your own custom **dataset.py** function in  **LASER_finetuning/dataset.py.**  You can see the given one for LibriSpeech as a  reference. Modify it as per your dataset such  that your __getitem()__function returns the original waveform and the augmented/perturbed waveform. Then just pass the address of your dataset. If you haven't worked in s3prl toolkit before, I would recommend to see their [downstream documentation](https://github.com/s3prl/s3prl/tree/main/s3prl/downstream)

**Comment by zxree** [comment]
Okay, I'll look into it.Thank you
